### ISSUE TITLE
API Key won't work

### ISSUE THREAD

**Issue by alizehctl** [brpaz/ulauncher-currency#1]
![image](https://user-images.githubusercontent.com/31581044/44645823-9e2e5980-aa0b-11e8-9f00-f8a69509a3a8.png)

The extension won't accept the API key from my fixer.io account for some reason. I tried resetting the key and using a new one, only to get the same error.

**Comment by 1stdante** [comment]
Same here.
![screenshot from 2018-11-30 02-11-22](https://user-images.githubusercontent.com/20787498/49245590-663d1500-f445-11e8-887e-bda69a409b87.png)

**Comment by brpaz** [comment]
This error normally indicates a missing dependency.

Please run the following from command line:

```pip install requests```

reopen ulauncher and try again.

If the problem persists, close ulauncher and from a terminal window run:

```ùlauncher -v```

Paste any output here, so I can analyze better whats the issue.

**Comment by pempek** [comment]
Hi! I'm facing similar issue. I'm using Manjaro and just installed Ulauncher from pamac.

This is what I got after running `ulauncher -v`:

`/usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib
`

**Comment by anachronic** [comment]
@brpaz would you consider changing the backend to a free api?

Like https://free.currencyconverterapi.com/ maybe? I'd be happy to send a PR.

I say this because last time I tried the extension it didn't work for me, but I haven't tried lately, instead I just changed the endpoint.

**Comment by SonephetR2** [comment]
Hi,

Same issue on Linux Mint. _pip install requests >> relaunch_ didn't work out for me.

@anachronic: would you mind sharing how you changed the endpoint?

Cheers,

**Comment by Prn-Ice** [comment]
Heres the output of ulauncher -v from the moment I attempt to activate plugin
```sh
2019-06-15 02:22:51,204 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2019-06-15 02:22:51,205 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1366, H: 768
2019-06-15 02:22:51,209 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2019-06-15 02:22:53,909 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2019-06-15 02:22:53,936 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2019-06-15 02:22:53,936 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2019-06-15 02:22:54,061 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2019-06-15 02:22:54,062 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2019-06-15 02:22:54,069 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2019-06-15 02:22:54,071 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2019-06-15 02:22:54,380 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2019-06-15 02:22:56,475 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_get_all() | Handling /extension/get-all
2019-06-15 02:23:04,847 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_update_prefs() | Update extension preferences: {'callback': '__jp2', 'id': 'com.github.brpaz.ulauncher-currency', 'pref.kw': 'currency', 'pref.api_key': '82f164fb149de4344ae15a70ab3c016e'}
2019-06-15 02:23:04,847 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. KeyError: com.github.brpaz.ulauncher-currency
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/site-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 368, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python2.7/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-currency'
```

**Comment by brpaz** [comment]
The latest version of Ulauncher and this extension requires Python 3. According to your logs, it seems you are using Python 2.7.

The latest version of Ulauncher also shows a better error indicating a missing Python package, when installing.

I will close this for now. Feel free to create a new issue if the problem persists.
